### ISSUE TITLE
Error opening a topic.

### ISSUE THREAD

**Issue by slaweally** [mentionbb/mentionbb#11] opened 2024-12-14 00:20 UTC
### Which MentionBB version?

1.0.21 Beta

### Description

When opening a new topic in the forum, the process does not complete, it gives a json output error:  Json response indicated that an error was returned.

**Comment by par274** [comment] 2024-12-14 10:02
When I tried it right now, I successfully opened 2 topics. I even tested it with a new membership and it was successful again.

If you can send the details you wrote in the content, the title, etc., here. You can send it as txt from here. This way I can see what is causing the error in the system.

**Comment by slaweally** [comment] 2024-12-16 10:07
Warning: DOMDocumentFragment::appendXML(): Entity: line 19: parser error : attributes construct error (500 Internal Server Error)
in /var/www/vhosts/mentionbb.com/httpdocs/src/App/Hook/Html.php (line 96) 

`

                $node->appendChild($fragment);
            }
        }
        public function prepend($class, object $replace)
        {
            $nodes = $this->getXPath($class);
            foreach ($nodes as $node)
            {
                $fragment = $this->dom->createDocumentFragment();
                $fragment->appendXML(FilterTag::filterSingleTags($replace()));
                $node->insertBefore($fragment, $node->firstChild);
            }
        }
        public function remove($class)
        {
            $nodes = $this->getXPath($class);
            foreach ($nodes as $node)
            {
                $node->parentNode->removeChild($node);

`

**Comment by par274** [comment] 2024-12-16 10:10
> Warning: DOMDocumentFragment::appendXML(): Entity: line 19: parser error : attributes construct error (500 Internal Server Error) in /var/www/vhosts/mentionbb.com/httpdocs/src/App/Hook/Html.php (line 96)
> 
> `
> 
> ```
>             $node->appendChild($fragment);
>         }
>     }
>     public function prepend($class, object $replace)
>     {
>         $nodes = $this->getXPath($class);
>         foreach ($nodes as $node)
>         {
>             $fragment = $this->dom->createDocumentFragment();
>             $fragment->appendXML(FilterTag::filterSingleTags($replace()));
>             $node->insertBefore($fragment, $node->firstChild);
>         }
>     }
>     public function remove($class)
>     {
>         $nodes = $this->getXPath($class);
>         foreach ($nodes as $node)
>         {
>             $node->parentNode->removeChild($node);
> ```
> 
> `

No, no. I don't think this is the cause of the error. Probably some "content" in the topic content is not rendering properly.

Because we can open a topic normally and we can use the prepend() method in plugins.

So, send the content you used when opening a topic here as txt. That way I can see what's causing it.

**Comment by slaweally** [comment] 2024-12-16 10:15
https://github.com/mentionbb/mentionbb;

I just wanted to share the document in the install section in readme.md. also in the topic update in the same way

**Comment by par274** [comment] 2024-12-16 10:17
> https://github.com/mentionbb/mentionbb;
> 
> I just wanted to share the document in the install section in readme.md. also in the topic update in the same way

Did you write the entire readme.md content?

**Comment by slaweally** [comment] 2024-12-16 10:21
no, the content between install and framework. But it doesn't matter, it's not very nice to have this kind of problem when users are copying and sharing stuff from anywhere :).

I also think it would be better if the editor section was bigger and it would make more sense to be embedded in the page, not with pop ups, because it's a bit more social media style as it is. 
This is just my personal opinion so we can discuss this individually :))

**Comment by par274** [comment] 2024-12-16 10:28
> no, the content between install and framework. But it doesn't matter, it's not very nice to have this kind of problem when users are copying and sharing stuff from anywhere :).
> 
> I also think it would be better if the editor section was bigger and it would make more sense to be embedded in the page, not with pop ups, because it's a bit more social media style as it is. This is just my personal opinion so we can discuss this individually :))

Of course, such a problem should not occur, but this cannot be foreseen and predicted, it is found with testing and debugging. In other words, the error is seen and solved. In fact, I just copied the entire readme.md content and successfully opened the topic.

It probably gives an error because it is caught in the filter due to one character, but as I said, I need to know which one to fix it.

Normally the method that gives an error is: \App\Hook\HTML::prepend(). But if this was broken, rest assured that none of the installed plugins would work. Especially the "Debug" on the header section.

**Comment by par274** [comment] 2024-12-16 14:22
All rendering problems, including this issue, were fixed with the following commits: 

- [Fix single tags](https://github.com/mentionbb/mentionbb/commit/efe17b47edbaeb4f1c5c744cfbd208893fbe6577)
- [Fix link renderer cache and image null](https://github.com/mentionbb/mentionbb/commit/d98ec9284efacfe80c85f288afb422ada525481f)
- [Fix multi-line pre tag](https://github.com/mentionbb/mentionbb/commit/b1351d836fb05762474e2253ddc2c65dafbafcd9)

https://mentionbb.com/d/186-how-to-mentionbb-install/337

This is caused by the Issue Typography(links to head tags) plugin. It was found that the html tags such as disabled and required, which stand alone, were interpreted incorrectly by the DOM renderer.

I don't know how permanent this fix is, report it if you encounter it again.

**Closed as completed by par274** 2024-12-16 14:22 UTC
Labels: bug
